<a href="https://colab.research.google.com/github/anastasiabf/Natural-Language-Processing-Projects/blob/main/Restaurant_Recommendation_System_using_Cosine_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CONTENT BASED**

fetch the dataset

In [38]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00232/RCdata.zip

--2023-08-16 13:57:23--  https://archive.ics.uci.edu/ml/machine-learning-databases/00232/RCdata.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘RCdata.zip.2’

RCdata.zip.2            [ <=>                ]  38.74K  --.-KB/s    in 0.1s

2023-08-16 13:57:24 (382 KB/s) - ‘RCdata.zip.2’ saved [39674]

In [39]:
!unzip /content/RCdata.zip

Archive:  /content/RCdata.zip
replace chefmozaccepts.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chefmozaccepts.csv
replace chefmozcuisine.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chefmozcuisine.csv
replace chefmozhours4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chefmozhours4.csv
replace chefmozparking.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chefmozparking.csv
replace geoplaces2.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: geoplaces2.csv
replace rating_final.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: rating_final.csv
replace README? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: README
replace usercuisine.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: usercuisine.csv
replace userpayment.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: userpayment.csv
replace userprofile.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: userprofile.csv

In [82]:
import pandas as pd

accepts = pd.read_csv('/content/chefmozaccepts.csv')
cuisine = pd.read_csv('/content/chefmozcuisine.csv')
hours = pd.read_csv('/content/chefmozhours4.csv')
parking = pd.read_csv('/content/chefmozparking.csv')
geo = pd.read_csv('/content/geoplaces2.csv', encoding = "ISO-8859-1")
usercuisine = pd.read_csv('/content/usercuisine.csv')
payment = pd.read_csv('/content/userpayment.csv')
profile = pd.read_csv('/content/userprofile.csv')
rating = pd.read_csv('/content/rating_final.csv')

print('Number of unique payment data received by restaurants: ', len(accepts.placeID.unique()))
print('Number of unique cuisines in restaurants: ', len(cuisine.placeID.unique()))
print('Number of unique restaurant opening hours data: ', len(hours.placeID.unique()))
print('Number of unique restaurant locations: ', len(geo.placeID.unique()))
print('Number of unique user cuisines data: ', len(usercuisine.userID.unique()))
print('Number of unique user profiles: ', len(profile.userID.unique()))
print('Number of unique ratings given by users: ', len(rating.userID.unique()))
print('Number of unique restaurant ratings: ', len(rating.placeID.unique()))

Number of unique payment data received by restaurants:  615
Number of unique cuisines in restaurants:  769
Number of unique restaurant opening hours data:  694
Number of unique restaurant locations:  130
Number of unique user cuisines data:  138
Number of unique user profiles:  138
Number of unique ratings given by users:  138
Number of unique restaurant ratings:  130

In [41]:
accepts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   1314 non-null   int64
 1   Rpayment  1314 non-null   object
dtypes: int64(1), object(1)
memory usage: 20.7+ KB

In [83]:
print('Amount of data: ', len(accepts.placeID.unique()))
print('Types of accepted payment methods: ', accepts.Rpayment.unique())

Amount of data:  615
Types of accepted payment methods:  ['cash' 'VISA' 'MasterCard-Eurocard' 'American_Express' 'bank_debit_cards'
 'checks' 'Discover' 'Carte_Blanche' 'Diners_Club' 'Visa'
 'Japan_Credit_Bureau' 'gift_certificates']

In [43]:
cuisine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   916 non-null    int64
 1   Rcuisine  916 non-null    object
dtypes: int64(1), object(1)
memory usage: 14.4+ KB

In [84]:
print('Number of cuisine types: ', len(cuisine.Rcuisine.unique()))
print('Cuisine types: ', cuisine.Rcuisine.unique())

Number of cuisine types:  59
Cuisine types:  ['Spanish' 'Italian' 'Latin_American' 'Mexican' 'Fast_Food' 'Burgers'
 'Dessert-Ice_Cream' 'Hot_Dogs' 'Steaks' 'Asian' 'International'
 'Mongolian' 'Vegetarian' 'Brazilian' 'Cafe-Coffee_Shop' 'Cafeteria'
 'Contemporary' 'Deli-Sandwiches' 'Diner' 'Japanese' 'Sushi' 'Seafood'
 'Chinese' 'Bar' 'Bar_Pub_Brewery' 'Pizzeria' 'Mediterranean' 'American'
 'Family' 'Caribbean' 'African' 'Breakfast-Brunch' 'Regional' 'Afghan'
 'Bakery' 'Game' 'Armenian' 'Vietnamese' 'Korean' 'Thai' 'Barbecue'
 'Polish' 'Dutch-Belgian' 'French' 'German' 'Southwestern' 'Persian'
 'Ethiopian' 'Juice' 'Soup' 'Continental-European' 'Greek' 'Southern'
 'Eastern_European' 'California' 'Bagels' 'Turkish' 'Organic-Healthy'
 'Fine_Dining']

In [45]:
print(profile.shape)

(138, 19)

In [46]:
profile.head()

,userID,latitude,longitude,smoker,drink_level,dress_preference,ambience,transport,marital_status,hijos,birth_year,interest,personality,religion,activity,color,weight,budget,height
0,U1001,22.139997,-100.978803,false,abstemious,informal,family,on foot,single,independent,1989,variety,thrifty-protector,none,student,black,69,medium,1.77
1,U1002,22.150087,-100.983325,false,abstemious,informal,family,public,single,independent,1990,technology,hunter-ostentatious,Catholic,student,red,40,low,1.87
2,U1003,22.119847,-100.946527,false,social drinker,formal,family,public,single,independent,1989,none,hard-worker,Catholic,student,blue,60,low,1.69
3,U1004,18.867000,-99.183000,false,abstemious,informal,family,public,single,independent,1940,variety,hard-worker,none,professional,green,44,medium,1.53
4,U1005,22.183477,-100.959891,false,abstemious,no preference,family,public,single,independent,1992,none,thrifty-protector,Catholic,student,black,65,medium,1.69

In [47]:
rating.head()

  userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [48]:
rating.describe()

             placeID       rating  food_rating  service_rating
count    1161.000000  1161.000000  1161.000000     1161.000000
mean   134192.041344     1.199828     1.215332        1.090439
std      1100.916275     0.773282     0.792294        0.790844
min    132560.000000     0.000000     0.000000        0.000000
25%    132856.000000     1.000000     1.000000        0.000000
50%    135030.000000     1.000000     1.000000        1.000000
75%    135059.000000     2.000000     2.000000        2.000000
max    135109.000000     2.000000     2.000000        2.000000

In [85]:
print('Number of unique userIDs: ', len(rating.userID.unique()))
print('Number of unique placeIDs: ', len(rating.placeID.unique()))
print('Number of rating data: ', len(rating))

Number of unique userIDs:  138
Number of unique placeIDs:  130
Number of rating data:  1161

In [86]:
import numpy as np

# combine all placeID in restaurant category
resto_all = np.concatenate((
    accepts.placeID.unique(),
    cuisine.placeID.unique(),
    hours.placeID.unique(),
    parking.placeID.unique(),
    geo.placeID.unique()
))

# sort data and delete same data
resto_all = np.sort(np.unique(resto_all))

print('Total number of restaurant data based on placeID: ', len(resto_all))

Total number of restaurant data based on placeID:  938

In [88]:
# combine all userID
user_all = np.concatenate((
    usercuisine.userID.unique(),
    payment.userID.unique(),
    profile.userID.unique()
))

# sort data and delete same data
user_all = np.sort(np.unique(user_all))

print('Total number of users: ', len(user_all))

Total number of users:  138

In [89]:
# Combining files accepts, geo, parking, hours into the dataframe resto_info
resto_info = pd.concat([accepts, geo, parking, hours])

# Merging the rating dataframe with resto_info based on the placeID value
resto = pd.merge(rating, resto_info, on='placeID', how='left')
resto

,userID,placeID,rating,food_rating,service_rating,Rpayment,latitude,longitude,the_geom_meter,name,...,accessibility,price,url,Rambience,franchise,area,other_services,parking_lot,hours,days
0,U1077,135085,2,2,2,cash,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,U1077,135085,2,2,2,NaN,22.150802,-100.982680,0101000020957F00009F823DA6094858C18A2D4D37F9A4...,Tortas Locas Hipocampo,...,no_accessibility,medium,?,familiar,f,closed,none,NaN,NaN,NaN
2,U1077,135085,2,2,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,public,NaN,NaN
3,U1077,135085,2,2,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00-00:00;,Mon;Tue;Wed;Thu;Fri;
4,U1077,135085,2,2,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00-00:00;,Sat;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8073,U1068,132660,0,0,0,NaN,23.752943,-99.164679,0101000020957F00003D7905C9DC8157C13FCD1AB7334E...,carnitas mata calle Emilio Portes Gil,...,completely,low,?,familiar,f,closed,none,NaN,NaN,NaN
8074,U1068,132660,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,none,NaN,NaN
8075,U1068,132660,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00-23:30;,Mon;Tue;Wed;Thu;Fri;
8076,U1068,132660,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00-23:30;,Sat;
8077,U1068,132660,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00:00-23:30;,Sun;

In [53]:
# Check missing value with isnull()
resto.isnull().sum()

userID               0
placeID              0
rating               0
food_rating          0
service_rating       0
Rpayment          5781
latitude          6917
longitude         6917
the_geom_meter    6917
name              6917
address           6917
city              6917
state             6917
country           6917
fax               6917
zip               6917
alcohol           6917
smoking_area      6917
dress_code        6917
accessibility     6917
price             6917
url               6917
Rambience         6917
franchise         6917
area              6917
other_services    6917
parking_lot       6917
hours             4619
days              4619
dtype: int64

In [90]:
# Calculating the sum of ratings, food_rating, and service, then merging them based on placeID
resto_grouped = resto.groupby('placeID').sum()

<ipython-input-90-67a1f3341eac>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  resto_grouped = resto.groupby('placeID').sum()

In [91]:
# Define the rating dataframe and assign it to the variable all_resto_rate
all_resto_rate = rating
all_resto_rate

     userID  placeID  rating  food_rating  service_rating
0     U1077   135085       2            2               2
1     U1077   135038       2            2               1
2     U1077   132825       2            2               2
3     U1077   135060       1            2               2
4     U1068   135104       1            1               2
...     ...      ...     ...          ...             ...
1156  U1043   132630       1            1               1
1157  U1011   132715       1            1               0
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

[1161 rows x 5 columns]

In [92]:
# Merging all_resto_rate with the geo dataframe based on placeID
all_resto_name = pd.merge(all_resto_rate, geo[['placeID', 'name']], on='placeID', how='left')

# Print the all_resto_name dataframe
print(all_resto_name)

     userID  placeID  rating  food_rating  service_rating  \
0     U1077   135085       2            2               2
1     U1077   135038       2            2               1
2     U1077   132825       2            2               2
3     U1077   135060       1            2               2
4     U1068   135104       1            1               2
...     ...      ...     ...          ...             ...
1156  U1043   132630       1            1               1
1157  U1011   132715       1            1               0
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

                                       name
0                    Tortas Locas Hipocampo
1                     Restaurant la Chalita
2                           puesto de tacos
3                   Restaurante Marisco Sam
4                                      vips
...                                     ...
1156                             palomo tec
1157                   tacos de la estacion
1158                          Little Cesarz
1159     tacos de barbacoa enfrente del Tec
1160  carnitas mata calle Emilio Portes Gil

[1161 rows x 6 columns]

In [93]:
# Merging the cuisine dataframe with all_resto_name and storing it in the variable all_resto
all_resto = pd.merge(all_resto_name, cuisine, on='placeID', how='left')
all_resto

,userID,placeID,rating,food_rating,service_rating,name,Rcuisine
0,U1077,135085,2,2,2,Tortas Locas Hipocampo,Fast_Food
1,U1077,135038,2,2,1,Restaurant la Chalita,NaN
2,U1077,132825,2,2,2,puesto de tacos,Mexican
3,U1077,135060,1,2,2,Restaurante Marisco Sam,Seafood
4,U1068,135104,1,1,2,vips,Mexican
...,...,...,...,...,...,...,...
1326,U1043,132630,1,1,1,palomo tec,Mexican
1327,U1011,132715,1,1,0,tacos de la estacion,Mexican
1328,U1068,132733,1,1,0,Little Cesarz,Pizzeria
1329,U1068,132594,1,1,1,tacos de barbacoa enfrente del Tec,Mexican
1330,U1068,132660,0,0,0,carnitas mata calle Emilio Portes Gil,NaN

In [58]:
# check missing value with isnull
all_resto.isnull().sum()

userID              0
placeID             0
rating              0
food_rating         0
service_rating      0
name                0
Rcuisine          288
dtype: int64

In [59]:
# clean missing value with dropna()
all_resto_clean = all_resto.dropna()
all_resto_clean

,userID,placeID,rating,food_rating,service_rating,name,Rcuisine
0,U1077,135085,2,2,2,Tortas Locas Hipocampo,Fast_Food
2,U1077,132825,2,2,2,puesto de tacos,Mexican
3,U1077,135060,1,2,2,Restaurante Marisco Sam,Seafood
4,U1068,135104,1,1,2,vips,Mexican
5,U1068,132740,0,0,0,Carreton de Flautas y Migadas,Mexican
...,...,...,...,...,...,...,...
1325,U1043,132732,1,1,1,Taqueria EL amigo,Mexican
1326,U1043,132630,1,1,1,palomo tec,Mexican
1327,U1011,132715,1,1,0,tacos de la estacion,Mexican
1328,U1068,132733,1,1,0,Little Cesarz,Pizzeria
1329,U1068,132594,1,1,1,tacos de barbacoa enfrente del Tec,Mexican

In [60]:
# check again missing value in variabel all_resto_clean
all_resto_clean.isnull().sum()

userID            0
placeID           0
rating            0
food_rating       0
service_rating    0
name              0
Rcuisine          0
dtype: int64

In [94]:
# Sorting the resto based on PlaceID and storing it in the variable fix_resto
fix_resto = all_resto_clean.sort_values('placeID', ascending=True)
fix_resto

,userID,placeID,rating,food_rating,service_rating,name,Rcuisine
1303,U1087,132560,1,2,1,puesto de gorditas,Regional
1288,U1050,132560,0,2,0,puesto de gorditas,Regional
14,U1067,132560,1,0,0,puesto de gorditas,Regional
42,U1082,132560,0,0,0,puesto de gorditas,Regional
1052,U1013,132572,1,1,0,Cafe Chaires,Cafeteria
...,...,...,...,...,...,...,...
438,U1024,135106,1,1,1,El Rincón de San Francisco,Mexican
178,U1020,135109,2,2,1,Paniroles,Italian
1071,U1041,135109,1,2,1,Paniroles,Italian
99,U1030,135109,0,0,0,Paniroles,Italian
180,U1051,135109,1,1,1,Paniroles,Italian

In [62]:
# check how much fix_resto
len(fix_resto.placeID.unique())

95

In [63]:
# Check unique cuisine categories
fix_resto.Rcuisine.unique()

array(['Regional', 'Cafeteria', 'American', 'Mexican', 'Fast_Food',
       'Italian', 'Armenian', 'Pizzeria', 'Japanese', 'Vietnamese',
       'Family', 'International', 'Game', 'Burgers', 'Bakery', 'Bar',
       'Breakfast-Brunch', 'Bar_Pub_Brewery', 'Mediterranean',
       'Cafe-Coffee_Shop', 'Contemporary', 'Seafood', 'Chinese'],
      dtype=object)

In [64]:
# Checking cuisine category 'Game'
fix_resto[fix_resto['Rcuisine'] == 'Game']

     userID  placeID  rating  food_rating  service_rating name Rcuisine
781   U1015   132851       1            1               1  KFC     Game
509   U1052   132851       1            0               2  KFC     Game
708   U1008   132851       1            1               1  KFC     Game
770   U1037   132851       2            2               1  KFC     Game
574   U1069   132851       1            0               0  KFC     Game
1188  U1131   132851       2            2               2  KFC     Game
764   U1111   132851       2            1               0  KFC     Game

In [65]:
# Checking cuisine categories for the restaurant named 'KFC'
fix_resto[fix_resto['name'] == 'KFC']

     userID  placeID  rating  food_rating  service_rating name  Rcuisine
781   U1015   132851       1            1               1  KFC      Game
508   U1052   132851       1            0               2  KFC  American
780   U1015   132851       1            1               1  KFC  American
509   U1052   132851       1            0               2  KFC      Game
708   U1008   132851       1            1               1  KFC      Game
707   U1008   132851       1            1               1  KFC  American
770   U1037   132851       2            2               1  KFC      Game
769   U1037   132851       2            2               1  KFC  American
1187  U1131   132851       2            2               2  KFC  American
574   U1069   132851       1            0               0  KFC      Game
1188  U1131   132851       2            2               2  KFC      Game
764   U1111   132851       2            1               0  KFC      Game
763   U1111   132851       2            1               0  KFC  American
573   U1069   132851       1            0               0  KFC  American

In [66]:
# Changing the cuisine category name 'Game' to 'American'
fix_resto = fix_resto.replace('Game', 'American')
fix_resto[fix_resto['name'] == 'KFC']

     userID  placeID  rating  food_rating  service_rating name  Rcuisine
781   U1015   132851       1            1               1  KFC  American
508   U1052   132851       1            0               2  KFC  American
780   U1015   132851       1            1               1  KFC  American
509   U1052   132851       1            0               2  KFC  American
708   U1008   132851       1            1               1  KFC  American
707   U1008   132851       1            1               1  KFC  American
770   U1037   132851       2            2               1  KFC  American
769   U1037   132851       2            2               1  KFC  American
1187  U1131   132851       2            2               2  KFC  American
574   U1069   132851       1            0               0  KFC  American
1188  U1131   132851       2            2               2  KFC  American
764   U1111   132851       2            1               0  KFC  American
763   U1111   132851       2            1               0  KFC  American
573   U1069   132851       1            0               0  KFC  American

In [67]:
# Creating a variable 'preparation' containing the fix_resto dataframe and then sorting it based on placeID
preparation = fix_resto
preparation.sort_values('placeID')

,userID,placeID,rating,food_rating,service_rating,name,Rcuisine
1303,U1087,132560,1,2,1,puesto de gorditas,Regional
1288,U1050,132560,0,2,0,puesto de gorditas,Regional
14,U1067,132560,1,0,0,puesto de gorditas,Regional
42,U1082,132560,0,0,0,puesto de gorditas,Regional
184,U1055,132572,2,2,2,Cafe Chaires,Cafeteria
...,...,...,...,...,...,...,...
1224,U1002,135106,1,1,1,El Rincón de San Francisco,Mexican
99,U1030,135109,0,0,0,Paniroles,Italian
178,U1020,135109,2,2,1,Paniroles,Italian
1071,U1041,135109,1,2,1,Paniroles,Italian
180,U1051,135109,1,1,1,Paniroles,Italian

In [68]:
# Removing duplicate data from the 'preparation' variable
preparation = preparation.drop_duplicates('placeID')
preparation

,userID,placeID,rating,food_rating,service_rating,name,Rcuisine
1303,U1087,132560,1,2,1,puesto de gorditas,Regional
1052,U1013,132572,1,1,0,Cafe Chaires,Cafeteria
168,U1118,132583,0,0,0,McDonalds Centro,American
24,U1107,132584,2,2,2,Gorditas Dona Tota,Mexican
1329,U1068,132594,1,1,1,tacos de barbacoa enfrente del Tec,Mexican
...,...,...,...,...,...,...,...
681,U1095,135086,1,2,1,Mcdonalds Parque Tangamanga,Fast_Food
175,U1020,135088,1,2,0,Cafeteria cenidet,Cafeteria
4,U1068,135104,1,1,2,vips,Mexican
488,U1004,135106,2,2,2,El Rincón de San Francisco,Mexican
178,U1020,135109,2,2,1,Paniroles,Italian

In [69]:
# Converting the 'placeID' data series into a list
resto_id = preparation['placeID'].tolist()

# Converting the 'Name' data series into a list
resto_name = preparation['name'].tolist()

# Converting the 'Rcuisine' data series into a list
resto_cuisine = preparation['Rcuisine'].tolist()

# Printing the lengths of the converted lists
print(len(resto_id))
print(len(resto_name))
print(len(resto_cuisine))

95
95
95

In [70]:
# Creating a dictionary for the data 'resto_id', 'resto_name', and 'cuisine'
resto_new = pd.DataFrame({
    'id': resto_id,
    'resto_name': resto_name,
    'cuisine': resto_cuisine
})
resto_new

        id                          resto_name    cuisine
0   132560                  puesto de gorditas   Regional
1   132572                        Cafe Chaires  Cafeteria
2   132583                    McDonalds Centro   American
3   132584                  Gorditas Dona Tota    Mexican
4   132594  tacos de barbacoa enfrente del Tec    Mexican
..     ...                                 ...        ...
90  135086         Mcdonalds Parque Tangamanga  Fast_Food
91  135088                   Cafeteria cenidet  Cafeteria
92  135104                                vips    Mexican
93  135106          El Rincón de San Francisco    Mexican
94  135109                           Paniroles    Italian

[95 rows x 3 columns]

In [71]:
data = resto_new
data.sample(5)

        id                               resto_name           cuisine
26  132773                              El cotorreo           Mexican
22  132755                     La Estrella de Dimas           Mexican
79  135058                     Restaurante Tiberius          Pizzeria
62  135030                 Preambulo Wifi Zone Cafe  Cafe-Coffee_Shop
77  135055  la Cochinita Pibil Restaurante Yucateco           Mexican

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TfidfVectorizer
tf = TfidfVectorizer()

# Calculate idf on the 'cuisine' data
tf.fit(data['cuisine'])

# Retrieve the feature names
feature_names = tf.get_feature_names_out()

# Print the feature names
print(feature_names)

['american' 'armenian' 'bar' 'bar_pub_brewery' 'breakfast' 'brunch'
 'burgers' 'cafe' 'cafeteria' 'chinese' 'coffee_shop' 'contemporary'
 'family' 'fast_food' 'international' 'italian' 'japanese' 'mexican'
 'pizzeria' 'regional' 'seafood' 'vietnamese']

In [95]:
# Fit and transform the data into a TF-IDF matrix
tfidf_matrix = tf.fit_transform(data['cuisine'])

# Check the size of the TF-IDF matrix
print(tfidf_matrix.shape)

(95, 22)

In [74]:
# Convert the TF-IDF vectorized matrix into dense matrix format
tfidf_matrix.todense()

matrix([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
# Create a DataFrame to visualize the tf-idf matrix
tfidf_df = pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names_out(),
    index=data['resto_name']
)

In [77]:
from sklearn.metrics.pairwise import cosine_similarity

# calculate cosine similarity on matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
# Create a DataFrame from the cosine_sim variable with restaurant names as rows and columns
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['resto_name'], columns=data['resto_name'])
print('Shape:', cosine_sim_df.shape)

# Display a sample of the similarity matrix for each restaurant
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

Shape: (95, 95)

resto_name,Gorditas Dona Tota,Sushi Itto,Restaurante El Reyecito,Dominos Pizza,Koye Sushi
resto_name,,,,,
Mariscos El Pescador,0.0,0.0,0.0,0.0,0.0
La Posada del Virrey,0.0,0.0,0.0,0.0,0.0
la parroquia,0.0,0.0,0.0,0.0,0.0
Mariscos Tia Licha,0.0,0.0,0.0,0.0,0.0
Restaurante de Mariscos la Langosta,0.0,0.0,0.0,0.0,0.0
Preambulo Wifi Zone Cafe,0.0,0.0,0.0,0.0,0.0
Cafeteria cenidet,0.0,0.0,0.0,0.0,0.0
Hamburguesas Valle Dorado,0.0,0.0,0.0,0.0,0.0
Restaurant Orizatlan,1.0,0.0,0.0,0.0,0.0
Log Yin,0.0,0.0,0.0,0.0,0.0

In [96]:
def resto_recommendations(resto_name, similarity_data=cosine_sim_df, items=data[['resto_name', 'cuisine']], k=5):
    """
    Restaurant Recommendations based on similarity dataframe

    Parameters:
    ---
    resto_name : str
                Restaurant name (index of the similarity dataframe)
    similarity_data : pd.DataFrame (object)
                      Symmetric similarity dataframe with restaurants as both index and columns
    items : pd.DataFrame (object)
            Contains both names and other features used to define similarity
    k : int
        Number of recommendations to provide
    ---

    In this function, we take k with the highest similarity values
    on the given index (i).
    """

    # Retrieve data using argpartition to perform an indirect partition along the given axis
    # Convert the dataframe to numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:, resto_name].to_numpy().argpartition(
        range(-1, -k, -1))

    # Retrieve data with the highest similarity from the available index
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop resto_name so that the searched restaurant name doesn't appear in the recommendation list
    closest = closest.drop(resto_name, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

In [97]:
data[data.resto_name.eq('KFC')]

        id resto_name   cuisine
31  132851        KFC  American

In [99]:
# Get restaurant recommendations similar to "KFC"
recommendations_for_kfc = resto_recommendations("KFC")
print(recommendations_for_kfc)

           resto_name        cuisine
0                VIPS       American
1  tacos los volcanes       American
2     Pizzeria Julios       American
3             Sirlone  International
4    McDonalds Centro       American